# file name for zones table csv data input files, data will be combined into a single table
aggregate_zone_file_names:
  - ma.hbwprh.csv
  - ma.hbwprl.csv
  - ma.hbwprm.csv
  - ma.totemp.csv
  - parking_cost.csv
